import { mkdtempSync, readFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createCompositionPlanV2, createRenderBundleV2 } from './packages/render-planner/src/v2.ts';
import { deliveryPromiseForManifest } from '@joy-media/export-core';
import { inspectRenderedDelivery } from '@joy-media/production-quality';
import { INITIAL_EDITOR_PROJECT } from './apps/editor-web/src/editor-project.ts';
import { StaticWorkerMediaResolver } from './apps/worker/src/worker-media-resolver.ts';
import { renderBundleToFile } from './apps/render-host/src/index.ts';
function must(args){const r=spawnSync('ffmpeg',args,{encoding:'utf8'});if(r.status!==0) throw new Error(r.stderr)}
function media(d,n,c,f){const p=join(d,`${n}.mp4`);must(['-y','-v','error','-f','lavfi','-i',`color=c=${c}:s=64x36:r=30`,'-f','lavfi','-i',`sine=frequency=${f}:sample_rate=48000`,'-t','1','-c:v','libx264','-pix_fmt','yuv420p','-c:a','aac','-ac','2',p]);return p}
function image(d){const p=join(d,'overlay.png');must(['-y','-v','error','-f','lavfi','-i','color=c=yellow:s=12x12','-frames:v','1',p]);return p}
function tone(d){const p=join(d,'music.wav');must(['-y','-v','error','-f','lavfi','-i','sine=frequency=220:sample_rate=48000:duration=1','-c:a','pcm_s16le',p]);return p}
function goldenTimeline(){return {schemaVersion:0,id:'p3-golden',rootCompositionId:'root',compositions:{root:{id:'root',name:'P3',width:64,height:36,frameRate:{num:30,den:1},durationUs:600000,tracks:[{id:'track-0',kind:'video',order:0,enabled:true,clips:[{id:'intro',kind:'video',startUs:0,durationUs:300000,assetId:'clip-a',sourceInUs:0},{id:'product',kind:'video',startUs:300000,durationUs:300000,assetId:'clip-b',sourceInUs:0}]},{id:'caption-track',kind:'caption',order:1,enabled:true,clips:[{id:'caption',kind:'caption',startUs:0,durationUs:600000,captionDocumentId:'caption-doc'}]}]}}}}
function goldenVisual(){const base=INITIAL_EDITOR_PROJECT;return {...base,id:'p3-golden-visual',title:'P3 certified editor golden',compositions:{root:{...base.compositions.root,width:64,height:36,durationUs:600000,tracks:[{id:'caption-track',kind:'caption',name:'Captions',order:5,enabled:true,locked:false,clips:[{id:'caption',kind:'caption',startUs:0,durationUs:600000,captionDocumentId:'caption-doc'}]}]}},assets:{'clip-a':{id:'clip-a',kind:'video',displayName:'Source A'},'clip-b':{id:'clip-b',kind:'video',displayName:'Source B'},overlay:{id:'overlay',kind:'image',displayName:'B-roll overlay'},music:{id:'music',kind:'audio',displayName:'Music'}},visualObjects:{overlay:{id:'overlay',kind:'image',assetId:'overlay',transform:{x:4,y:4,scaleX:1,scaleY:1,rotationDeg:0,opacity:1,crop:{left:0,top:0,right:0,bottom:0}}},title:{id:'title',kind:'text',text:'JOY MEDIA',transform:{x:2,y:2,scaleX:1,scaleY:1,rotationDeg:0,opacity:1,crop:{left:0,top:0,right:0,bottom:0}}}},captionDocuments:{'caption-doc':{id:'caption-doc',language:'en',direction:'ltr',speakers:[],words:{word:{id:'word',text:'Corrected caption',startUs:0,endUs:600000}},segments:[{id:'segment',startUs:0,endUs:600000,wordIds:['word']}],styleRef:'joy-clean'}},pluginData:{'joy.captions.burnIn':true},colorGrade:{lift:0.05,gamma:1,gain:1,saturation:1.2},transitions:[{id:'dissolve',trackId:'track-0',leftClipId:'intro',rightClipId:'product',type:'dissolve',durationUs:100000,startUs:200000,endUs:300000}],audio:{clips:{intro:{gain:.8,pan:0,mute:false,solo:false,role:'dialogue'},product:{gain:.8,pan:0,mute:false,solo:false,role:'dialogue'},music:{gain:.35,pan:0,mute:false,solo:false,role:'music'}},buses:[],effects:[]}}}
const directory=mkdtempSync(join(tmpdir(),'joy-media-p3-debug-')); const a=media(directory,'a','red',440), b=media(directory,'b','blue',660), overlay=image(directory), music=tone(directory); const resolver=new StaticWorkerMediaResolver({'asset:clip-a':a,'asset:clip-b':b,'asset:overlay':overlay,'asset:music':music});
for (const [name,viewport] of [['landscape',{width:320,height:180}],['vertical',{width:180,height:320}]]){ const plan=createCompositionPlanV2({timelineProject:goldenTimeline(),visualProject:goldenVisual(),viewport}); const assets=Object.fromEntries(Object.entries({'clip-a':a,'clip-b':b,overlay,music}).map(([id,path])=>{const bytes=readFileSync(path); return [id,{assetId:id,opaqueRef:`asset:${id}`,integrity:{sha256:createHash('sha256').update(bytes).digest('hex'),bytes:bytes.length,mime:id==='overlay'?'image/png':id==='music'?'audio/wav':'video/mp4'}}]})); const bundle=createRenderBundleV2({plan,assets,projectRef:`p3-${name}`,revision:name==='landscape'?1:2}); const outputPath=join(directory,`p3-${name}.mp4`); const result=await renderBundleToFile({protocolVersion:1,bundle,outputPath,mediaResolver:resolver}); const promise={...deliveryPromiseForManifest(result.manifest),captions:{mode:'burned-in',required:true,burnIn:{styleRef:plan.captionBurnIn.styleRef,segments:plan.captionBurnIn.segments.map(({startUs,endUs,text,direction})=>({startUs,endUs,text,direction}))}}}; const report=inspectRenderedDelivery(outputPath,promise,{mode:'sampled',outputRef:'out'}); console.log(JSON.stringify({name,manifest:result.manifest,findings:report.findings,facts:report.facts.video},null,2)); }
