console.log('ENV:', {
  JOY_MEDIA_LOCAL_COMFY_URL: process.env.JOY_MEDIA_LOCAL_COMFY_URL,
  JOY_MEDIA_LOCAL_ML_DENOISE: process.env.JOY_MEDIA_LOCAL_ML_DENOISE,
  JOY_MEDIA_API_URL: process.env.JOY_MEDIA_API_URL,
  JOY_MEDIA_RNNOISE_MODEL: process.env.JOY_MEDIA_RNNOISE_MODEL
});