import type { CreativeBriefV1 } from '@joy-media/agent-tools';

/** Minimal complete brief, using the same intelligence contract as generated briefs. */
export function briefFixture(
  projectId: string,
  revisionId: string,
  request: string,
): CreativeBriefV1 {
  return {
    schemaVersion: 1,
    projectId,
    snapshotRevisionId: revisionId,
    request,
    interpretedGoal: {
      userIntent: request,
      inferredGoal: request,
      resolvedGoal: request,
      confidence: 'high',
    },
    distinction: { facts: [], inferences: [] },
    assumptions: [],
    recommendations: [],
    blockedBy: [],
    requiresHumanDecision: [],
    intelligence: {
      brand: {
        projectId,
        revisionId,
        colorsAvailable: false,
        fontsAvailable: false,
        logoAvailable: false,
        voiceInstructionsAvailable: false,
        toneInstructionsAvailable: false,
        prohibitedClaims: [],
        prohibitedEffects: [],
        hasBrandKit: false,
        brandCompleteness: 'none',
        missingComponents: [],
        warnings: [],
        evidence: [],
      },
      scenes: [],
      project: {
        projectId,
        revisionId,
        destination: undefined,
        destinationAligned: false,
        destinationMismatch: undefined,
        durationTargetUs: undefined,
        compositionDurationUs: 0,
        durationAligned: false,
        durationGapUs: undefined,
        aspectRatio: '16:9',
        aspectRatioAligned: false,
        aspectRatioMismatch: undefined,
        captionAvailable: false,
        audioAvailable: false,
        generatedAssetsAvailable: false,
        readinessLevel: 'unknown',
        blockers: [],
        warnings: [],
        sceneCount: 0,
        scenesWithVisuals: 0,
        scenesWithAudio: 0,
        scenesWithCaptions: 0,
        evidence: [],
      },
      rules: [],
    },
    warnings: [],
    meta: { generatedAt: '2026-09-05T00:00:00.000Z', modelAdapter: 'fixture', processingTimeMs: 0 },
  };
}
