import { iconUrl } from './icon-assets.js';
/**
 * Uploaded 24×24 UI PNGs under `public/assets/icons/ui/`.
 * Prefer these for panel tabs / mute-mic chrome; CSS-mask them with currentColor.
 */

export const UI_ICONS = {
  assets: iconUrl('assets.png'),
  camera: iconUrl('camera.png'),
  grid: iconUrl('ui/4squares_24x24.png'),
  aiEffect: iconUrl('ui/ai-effect_24x24.png'),
  agentAi: iconUrl('ui/agent-ai_24x24.png'),
  capcut: iconUrl('ui/capcut_24x24.png'),
  effects: iconUrl('ui/effects_24x24.png'),
  effectsAlt: iconUrl('ui/effects2_24x24.png'),
  effectsOrg: iconUrl('ui/effects-org_24x24.png'),
  motion: iconUrl('ui/motion_24x24.png'),
  mic: iconUrl('ui/mic_24x24.png'),
  mute: iconUrl('ui/mute_24x24.png'),
  settings: iconUrl('ui/setting-gear_24x24.png'),
  inspect: iconUrl('ui/inspect_24x24.png'),
  speakerOn: iconUrl('ui/speaker-on_24x24.png'),
  speaker: iconUrl('ui/speaker_24x24.png'),
  transition: iconUrl('ui/transition_24x24.png'),
  /** Canonical name; source upload was misspelled `voice-cion`. */
  voice: iconUrl('ui/voice-icon_24x24.png'),
  voiceMemo: iconUrl('ui/voice-memo_24x24.png'),
  text: iconUrl('ui/t_24x24.png'),
  colors: iconUrl('ui/colors_24x24.png'),
  add: iconUrl('ui/add+_24x24.png'),
  edit: iconUrl('ui/edit_24x24.png'),
  blend: iconUrl('ui/blend_24x24.png'),
  blur: iconUrl('ui/blur_24x24.png'),
  /** Filename keeps upstream typo `brighness`. */
  brightness: iconUrl('ui/brighness_24x24.png'),
  brushSize: iconUrl('ui/brush-size_24x24.png'),
  brushSizeAlt: iconUrl('ui/brush-size2_24x24.png'),
  contrast: iconUrl('ui/contrast_24x24.png'),
  crop: iconUrl('ui/crop_24x24.png'),
  fullscreen: iconUrl('ui/full-screen_24x24.png'),
  gain: iconUrl('ui/gain_24x24.png'),
  gamma: iconUrl('ui/gamma_24x24.png'),
  invertColor: iconUrl('ui/invert-color_24x24.png'),
  lift: iconUrl('ui/lift_24x24.png'),
  saturation: iconUrl('ui/saturation_24x24.png'),
  timeline: iconUrl('ui/time-line_24x24.png'),
  timelineAlt: iconUrl('ui/time-line2_24x24.png'),
  marker: iconUrl('ui/marker_24x24.png'),
  markerTimeline: iconUrl('ui/marker-timeline_24x24.png'),
  timelineVideo: iconUrl('ui/timeline-video_24x24.png'),
  timelineAudio: iconUrl('ui/timeline-audio_24x24.png'),
  timelineScript: iconUrl('ui/timeline-script_24x24.png'),
  flow: iconUrl('ui/flow_24x24.png'),
  programOutput: iconUrl('ui/output_24x24.png'),
  layers: iconUrl('24_layers.png'),

  /** Canva icon set, added 2026-07-28 for Motion Studio Phase 2+ (see plan/motion-studio-phase-2-7-handoff.md). */
  analysis: iconUrl('ui/analysis.png'),
  background: iconUrl('ui/background.png'),
  borderRadius: iconUrl('ui/border-radius.png'),
  brushSizeCanva: iconUrl('ui/brush-size-alt.png'),
  charts: iconUrl('ui/charts.png'),
  cloudSaved: iconUrl('ui/cloud-saved.png'),
  commentsCaption: iconUrl('ui/comments-caption.png'),
  createNew: iconUrl('ui/create-new.png'),
  cropCanva: iconUrl('ui/crop-alt.png'),
  deleteTrash: iconUrl('ui/delete-trash.png'),
  down: iconUrl('ui/down.png'),
  downAlt: iconUrl('ui/down-alt.png'),
  duplicateCanva: iconUrl('ui/duplicate.png'),
  duplicateCanvaAlt: iconUrl('ui/duplicate-alt.png'),
  folderAssets: iconUrl('ui/folder-assets.png'),
  fullscreenMode: iconUrl('ui/fullscreen-mode.png'),
  help: iconUrl('ui/help.png'),
  hidden: iconUrl('ui/hidden.png'),
  home: iconUrl('ui/home.png'),
  music: iconUrl('ui/music.png'),
  opacity: iconUrl('ui/opacity.png'),
  paint: iconUrl('ui/paint.png'),
  proVip: iconUrl('ui/pro-vip.png'),
  refreshRetry: iconUrl('ui/refresh-retry.png'),
  removeDelete: iconUrl('ui/remove-delete.png'),
  rightSidebar: iconUrl('ui/right-sidebar.png'),
  saveView: iconUrl('ui/save-view.png'),
  settingGearAlt: iconUrl('ui/setting-gear-alt.png'),
  stickers: iconUrl('ui/stickers.png'),
  textAlt: iconUrl('ui/text-alt.png'),
  threeDots: iconUrl('ui/three-dots.png'),
  timing: iconUrl('ui/timing.png'),
  unlockAlt: iconUrl('ui/unlock-alt.png'),
  unlock: iconUrl('ui/unlock.png'),
  up: iconUrl('ui/up.png'),
  uploadToCloud: iconUrl('ui/upload-to-cloud.png'),
  verticalView: iconUrl('ui/vertical-view.png'),
  videoCaptions: iconUrl('ui/video-captions.png'),
  wideView: iconUrl('ui/wide-view.png'),
} as const;

export type UiIconId = keyof typeof UI_ICONS;
