import type { EffectDescriptor } from '../types.js';

const FULL_RENDER_SUPPORT = {
  pixiPreview: true,
  headless: true,
  ffmpeg: false,
  deterministic: true,
} as const;

const BINARY_OPTIONS = [
  { label: 'Off', value: 0 },
  { label: 'On', value: 1 },
] as const;

export const monochromeDescriptor: EffectDescriptor = {
  id: 'monochrome',
  label: 'Monochrome Lab',
  category: 'artistic',
  description: 'Shape the image into crisp or softly rolled black and white tones.',
  params: [
    {
      key: 'threshold',
      label: 'Threshold',
      type: 'number',
      defaultValue: 0.5,
      min: 0,
      max: 1,
      step: 0.01,
      animatable: true,
    },
    {
      key: 'softness',
      label: 'Softness',
      type: 'number',
      defaultValue: 0.04,
      min: 0,
      max: 0.5,
      step: 0.01,
      animatable: true,
    },
    {
      key: 'contrast',
      label: 'Contrast',
      type: 'number',
      defaultValue: 0.2,
      min: -1,
      max: 2,
      step: 0.01,
      animatable: true,
    },
    {
      key: 'invert',
      label: 'Invert',
      type: 'enum',
      defaultValue: 0,
      options: BINARY_OPTIONS,
      animatable: false,
    },
  ],
  tags: ['black and white', 'bw', 'threshold', 'mono', 'xerox'],
  backend: FULL_RENDER_SUPPORT,
  cost: 'low',
};

export const bayerDitherDescriptor: EffectDescriptor = {
  id: 'bayer-dither',
  label: 'Bayer Dither',
  category: 'artistic',
  description: 'Ordered matrix dithering with stable, animation-friendly pixel patterns.',
  params: [
    {
      key: 'cellSize',
      label: 'Pixel Scale',
      type: 'number',
      defaultValue: 2,
      min: 1,
      max: 12,
      step: 1,
      animatable: true,
    },
    {
      key: 'levels',
      label: 'Tone Levels',
      type: 'number',
      defaultValue: 2,
      min: 2,
      max: 8,
      step: 1,
      animatable: true,
    },
    {
      key: 'strength',
      label: 'Pattern Strength',
      type: 'number',
      defaultValue: 1,
      min: 0,
      max: 1,
      step: 0.01,
      animatable: true,
    },
    {
      key: 'colorMode',
      label: 'Color',
      type: 'enum',
      defaultValue: 0,
      options: [
        { label: 'Monochrome', value: 0 },
        { label: 'Source Color', value: 1 },
      ],
      animatable: false,
    },
    {
      key: 'invert',
      label: 'Invert',
      type: 'enum',
      defaultValue: 0,
      options: BINARY_OPTIONS,
      animatable: false,
    },
  ],
  tags: ['dither', 'bayer', 'pixel', 'retro', 'black and white', 'bw'],
  backend: FULL_RENDER_SUPPORT,
  cost: 'low',
};

export const halftoneDescriptor: EffectDescriptor = {
  id: 'halftone',
  label: 'Halftone Press',
  category: 'artistic',
  description: 'Translate luminance into rotatable print dots, diamonds, or line screens.',
  params: [
    {
      key: 'cellSize',
      label: 'Screen Size',
      type: 'number',
      defaultValue: 10,
      min: 3,
      max: 40,
      step: 1,
      animatable: true,
    },
    {
      key: 'angle',
      label: 'Screen Angle',
      type: 'number',
      defaultValue: 22.5,
      min: -180,
      max: 180,
      step: 0.5,
      unit: 'deg',
      animatable: true,
    },
    {
      key: 'dotScale',
      label: 'Ink Spread',
      type: 'number',
      defaultValue: 1,
      min: 0.25,
      max: 1.8,
      step: 0.01,
      animatable: true,
    },
    {
      key: 'shape',
      label: 'Shape',
      type: 'enum',
      defaultValue: 0,
      options: [
        { label: 'Dots', value: 0 },
        { label: 'Diamonds', value: 1 },
        { label: 'Lines', value: 2 },
      ],
      animatable: false,
    },
    {
      key: 'colorMode',
      label: 'Ink',
      type: 'enum',
      defaultValue: 0,
      options: [
        { label: 'Black', value: 0 },
        { label: 'Source Color', value: 1 },
      ],
      animatable: false,
    },
    {
      key: 'invert',
      label: 'Invert',
      type: 'enum',
      defaultValue: 0,
      options: BINARY_OPTIONS,
      animatable: false,
    },
  ],
  tags: ['halftone', 'print', 'newsprint', 'dots', 'lines', 'black and white', 'bw'],
  backend: FULL_RENDER_SUPPORT,
  cost: 'medium',
};

export const contourMapDescriptor: EffectDescriptor = {
  id: 'contour-map',
  label: 'Contour Map',
  category: 'stylize',
  description: 'Combine topographic tone bands with image-aware Sobel edge lines.',
  params: [
    {
      key: 'spacing',
      label: 'Contour Count',
      type: 'number',
      defaultValue: 9,
      min: 2,
      max: 24,
      step: 1,
      animatable: true,
    },
    {
      key: 'thickness',
      label: 'Line Weight',
      type: 'number',
      defaultValue: 0.16,
      min: 0.02,
      max: 0.45,
      step: 0.01,
      animatable: true,
    },
    {
      key: 'edgeBoost',
      label: 'Edge Detail',
      type: 'number',
      defaultValue: 0.75,
      min: 0,
      max: 2,
      step: 0.01,
      animatable: true,
    },
    {
      key: 'detail',
      label: 'Sample Radius',
      type: 'number',
      defaultValue: 1,
      min: 1,
      max: 4,
      step: 1,
      animatable: true,
    },
    {
      key: 'invert',
      label: 'Invert',
      type: 'enum',
      defaultValue: 0,
      options: BINARY_OPTIONS,
      animatable: false,
    },
  ],
  tags: ['contour', 'topographic', 'edge', 'outline', 'terrain', 'black and white', 'bw'],
  backend: FULL_RENDER_SUPPORT,
  cost: 'medium',
};

export const glyphMatrixDescriptor: EffectDescriptor = {
  id: 'glyph-matrix',
  label: 'Glyph Matrix',
  category: 'stylize',
  description: 'Rebuild the source from procedural glyph cells, symbols, and flowing code marks.',
  params: [
    {
      key: 'cellWidth',
      label: 'Cell Width',
      type: 'number',
      defaultValue: 10,
      min: 4,
      max: 32,
      step: 1,
      animatable: true,
    },
    {
      key: 'cellHeight',
      label: 'Cell Height',
      type: 'number',
      defaultValue: 14,
      min: 6,
      max: 40,
      step: 1,
      animatable: true,
    },
    {
      key: 'density',
      label: 'Glyph Density',
      type: 'number',
      defaultValue: 1,
      min: 0.2,
      max: 2,
      step: 0.01,
      animatable: true,
    },
    {
      key: 'contrast',
      label: 'Source Contrast',
      type: 'number',
      defaultValue: 0.3,
      min: -1,
      max: 2,
      step: 0.01,
      animatable: true,
    },
    {
      key: 'style',
      label: 'Glyph Style',
      type: 'enum',
      defaultValue: 1,
      options: [
        { label: 'Dots', value: 0 },
        { label: 'Pixels', value: 1 },
        { label: 'Segments', value: 2 },
      ],
      animatable: false,
    },
    {
      key: 'flow',
      label: 'Vertical Flow',
      type: 'number',
      defaultValue: 0,
      min: 0,
      max: 1,
      step: 0.01,
      animatable: true,
    },
    {
      key: 'foregroundR',
      label: 'Ink Red',
      type: 'number',
      defaultValue: 110,
      min: 0,
      max: 255,
      step: 1,
      animatable: true,
    },
    {
      key: 'foregroundG',
      label: 'Ink Green',
      type: 'number',
      defaultValue: 255,
      min: 0,
      max: 255,
      step: 1,
      animatable: true,
    },
    {
      key: 'foregroundB',
      label: 'Ink Blue',
      type: 'number',
      defaultValue: 155,
      min: 0,
      max: 255,
      step: 1,
      animatable: true,
    },
    {
      key: 'colorMode',
      label: 'Color',
      type: 'enum',
      defaultValue: 0,
      options: [
        { label: 'Custom Ink', value: 0 },
        { label: 'Source Color', value: 1 },
      ],
      animatable: false,
    },
    {
      key: 'invert',
      label: 'Invert Source',
      type: 'enum',
      defaultValue: 0,
      options: BINARY_OPTIONS,
      animatable: false,
    },
  ],
  tags: ['glyph', 'ascii', 'matrix', 'symbol', 'code', 'rain', 'pixel'],
  backend: FULL_RENDER_SUPPORT,
  cost: 'medium',
};

export const scatterMosaicDescriptor: EffectDescriptor = {
  id: 'scatter-mosaic',
  label: 'Scatter Mosaic',
  category: 'stylize',
  description: 'Break the frame into offset color samples with controlled tonal reduction.',
  params: [
    {
      key: 'cellSize',
      label: 'Tile Size',
      type: 'number',
      defaultValue: 12,
      min: 4,
      max: 48,
      step: 1,
      animatable: true,
    },
    {
      key: 'scatter',
      label: 'Scatter',
      type: 'number',
      defaultValue: 0.75,
      min: 0,
      max: 2,
      step: 0.01,
      animatable: true,
    },
    {
      key: 'levels',
      label: 'Color Levels',
      type: 'number',
      defaultValue: 8,
      min: 2,
      max: 24,
      step: 1,
      animatable: true,
    },
    {
      key: 'colorMode',
      label: 'Color',
      type: 'enum',
      defaultValue: 1,
      options: [
        { label: 'Monochrome', value: 0 },
        { label: 'Source Color', value: 1 },
      ],
      animatable: false,
    },
    {
      key: 'seed',
      label: 'Pattern Seed',
      type: 'number',
      defaultValue: 3,
      min: 0,
      max: 20,
      step: 0.1,
      animatable: true,
    },
  ],
  tags: ['scatter', 'mosaic', 'pixel', 'tiles', 'poster', 'block'],
  backend: FULL_RENDER_SUPPORT,
  cost: 'low',
};

export const toneGeometryDescriptor: EffectDescriptor = {
  id: 'tone-geometry',
  label: 'Tone Geometry',
  category: 'artistic',
  description: 'Turn each sampled tone into circles, diamonds, crosses, or line geometry.',
  params: [
    {
      key: 'cellSize',
      label: 'Cell Size',
      type: 'number',
      defaultValue: 14,
      min: 5,
      max: 48,
      step: 1,
      animatable: true,
    },
    {
      key: 'scale',
      label: 'Shape Scale',
      type: 'number',
      defaultValue: 1,
      min: 0.25,
      max: 1.8,
      step: 0.01,
      animatable: true,
    },
    {
      key: 'angle',
      label: 'Angle',
      type: 'number',
      defaultValue: 0,
      min: -180,
      max: 180,
      step: 1,
      unit: 'deg',
      animatable: true,
    },
    {
      key: 'shape',
      label: 'Shape',
      type: 'enum',
      defaultValue: 0,
      options: [
        { label: 'Circle', value: 0 },
        { label: 'Diamond', value: 1 },
        { label: 'Cross', value: 2 },
        { label: 'Line', value: 3 },
      ],
      animatable: false,
    },
    {
      key: 'colorMode',
      label: 'Color',
      type: 'enum',
      defaultValue: 0,
      options: [
        { label: 'Black Ink', value: 0 },
        { label: 'Source Color', value: 1 },
      ],
      animatable: false,
    },
    {
      key: 'invert',
      label: 'Invert',
      type: 'enum',
      defaultValue: 0,
      options: BINARY_OPTIONS,
      animatable: false,
    },
  ],
  tags: ['tone', 'geometry', 'shape', 'dots', 'op art', 'black and white', 'bw'],
  backend: FULL_RENDER_SUPPORT,
  cost: 'medium',
};

export const pixelSortDescriptor: EffectDescriptor = {
  id: 'pixel-sort',
  label: 'Pixel Sort',
  category: 'distort',
  description: 'Stretch selected luminance ranges into directional, data-moshed pixel bands.',
  params: [
    {
      key: 'direction',
      label: 'Direction',
      type: 'enum',
      defaultValue: 1,
      options: [
        { label: 'Horizontal', value: 0 },
        { label: 'Vertical', value: 1 },
      ],
      animatable: false,
    },
    {
      key: 'lowThreshold',
      label: 'Shadow Gate',
      type: 'number',
      defaultValue: 0.18,
      min: 0,
      max: 1,
      step: 0.01,
      animatable: true,
    },
    {
      key: 'highThreshold',
      label: 'Highlight Gate',
      type: 'number',
      defaultValue: 0.9,
      min: 0,
      max: 1,
      step: 0.01,
      animatable: true,
    },
    {
      key: 'length',
      label: 'Sort Length',
      type: 'number',
      defaultValue: 72,
      min: 4,
      max: 240,
      step: 1,
      unit: 'px',
      animatable: true,
    },
    {
      key: 'intensity',
      label: 'Intensity',
      type: 'number',
      defaultValue: 1,
      min: 0,
      max: 1.5,
      step: 0.01,
      animatable: true,
    },
    {
      key: 'colorMode',
      label: 'Color',
      type: 'enum',
      defaultValue: 1,
      options: [
        { label: 'Monochrome', value: 0 },
        { label: 'Source Color', value: 1 },
      ],
      animatable: false,
    },
  ],
  tags: ['pixel sort', 'pixel', 'glitch', 'streak', 'datamosh', 'distort'],
  backend: FULL_RENDER_SUPPORT,
  cost: 'high',
};

export const CREATIVE_PIXEL_DESCRIPTORS: readonly EffectDescriptor[] = [
  monochromeDescriptor,
  bayerDitherDescriptor,
  halftoneDescriptor,
  contourMapDescriptor,
  glyphMatrixDescriptor,
  scatterMosaicDescriptor,
  toneGeometryDescriptor,
  pixelSortDescriptor,
];
